--- Tabla Prenda

CREATE TABLE SAMANDA.PRENDA (
   ID number generated by default on null as identity,
   TITULO VARCHAR(100) not null,
   CATEGORIA VARCHAR(50) not null,
   COSTO number not null,
   DESCRIPCION VARCHAR(400),
   
   PRIMARY KEY (ID)
);
